package com.example.sharyar_cardiobook;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;
import java.util.Date;
import java.util.Locale;


/*
Please note that most of the database system used in this program is based upon information from:

Author: CodeLabs by Google
Title: Android Room with a View - Java
Url: https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#0

There are some parts of the application where I also used the official reference documentation for
Android from their main site: https://developer.android.com/docs to understand the functionality
as well as implement functionality that I needed.
 */


/**
 * Main class that describes the a cardioRecord. It also serves as the table structure for the
 * room database as denoted by the @Entity decorator.
 */
@Entity(tableName = "cardio_record")
public class CardioRecord implements Serializable {

    // Autogenerated unique id for each record so they can be told apart in the databse when needed.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "UniqueId")
    private int id = 0;

    // Declare variables required
    private Date recordDate;
    private int systolic;
    private int diastolic;
    private int heartRate;
    private String comment;


    /**
     * Constructor for the class which initializes all the attributes based on arguments provided.
     *
     * @param date      record date
     * @param systolic  systolic pressure in mm Hg
     * @param diastolic diastolic pressure in mm Hg
     * @param heartRate heartrate in beats per min
     * @param comment   max 20 characters
     */
    public CardioRecord(Date date, int systolic, int diastolic, int heartRate, String comment) {
        this.recordDate = date;
        this.systolic = systolic;
        this.diastolic = diastolic;
        this.heartRate = heartRate;
        this.comment = comment;
    }

    /**
     * Default constructor that initializes a new cardioRecord object with no parameters. It does
     * autogenerate the id.
     */
    public CardioRecord() {
    }

    //getter and setter methods
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getRecordDate() {
        return this.recordDate;
    }

    public void setRecordDate(Date date) {
        this.recordDate = date;
    }

    public int getSystolic() {
        return this.systolic;
    }

    public void setSystolic(int systolic) {
        this.systolic = systolic;
    }

    public int getDiastolic() {
        return this.diastolic;
    }

    public void setDiastolic(int diastolic) {
        this.diastolic = diastolic;
    }

    public int getHeartRate() {
        return this.heartRate;
    }

    public void setHeartRate(int heartRate) {
        this.heartRate = heartRate;
    }


    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * ToString method override. I used this method to show a summary of
     *
     * @return String representation of cardioRecord.
     */
    @Override
    @NonNull
    public String toString() {
        String stringRepresentation;
        stringRepresentation = String.format(Locale.getDefault(), "Systolic: %d - " +
                        "Diastolic: %d - Heart Rate: %d - Comment: %s", systolic, diastolic,
                heartRate, comment);
        return stringRepresentation;
    }

}
